# Generated by Django 4.0.4 on 2022-06-28 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kozirki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(default='static/media/kozirki/default.webp', upload_to='static/media/kozirki')),
            ],
        ),
        migrations.CreateModel(
            name='Nerjograda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(default='static/media/nerjograda/default.webp', upload_to='static/media/nerjograda')),
            ],
        ),
        migrations.CreateModel(
            name='Peregorodki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(default='static/media/peregorodki/default.webp', upload_to='static/media/peregorodki')),
            ],
        ),
        migrations.CreateModel(
            name='Stekloograda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(default='static/media/stekloograda/default.webp', upload_to='static/media/stekloograda')),
            ],
        ),
    ]
